[tool.poetry]
name = "nisardev"
version = "0.0.8"
description = "Tools for NISAR/GrIMP L3 products"
authors = ["Ian Joughin <ian@apl.washington.edu>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/fastice/nisardev"
repository = "https://github.com/fastice/nisardev"
keywords = ["SAR", "NISAR"]

[tool.poetry.dependencies]
python = ">=3.7"
#dask = "^2021"
#pandas = "^1"
#progressbar2 = "^3"
#numpy = "^1.20.0"
#panel = "^0"
#requests = "^2"
#rioxarray = "^0"
#stackstac = "^0.2"
#xarray = "^0"

[tool.poetry.dev-dependencies]
ipython = "*"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.9"]
build-backend = "poetry.core.masonry.api"
#requires = ["setuptools", "poetry-core @ git+https://github.com/python-poetry/poetry-core.git@master"]

